// Core
export const COR_SET_ME = "COR_SET_ME";
export const COR_UPDATE_ME_BY_PROFILE = "COR_UPDATE_ME_BY_PROFILE";
export const COR_SET_MEMBER_ME = "COR_SET_MEMBER_ME";
export const COR_OPEN_SIDE_BAR = "COR_OPEN_SIDE_BAR";
export const COR_CLOSE_SIDE_BAR = "COR_CLOSE_SIDE_BAR";
export const COR_SET_MESSAGE = "COR_SET_MESSAGE";
export const CORE_SET_MESSAGE_ERROR_STATUS = "CORE_SET_MESSAGE_ERROR_STATUS";
export const CORE_SET_MESSAGE_ERROR = "CORE_SET_MESSAGE_ERROR";
export const COR_EMPTY_MESSAGE = "COR_EMPTY_MESSAGE";
export const COR_EMPTY_ERROR = "COR_EMPTY_ERROR";
export const COR_LOGOUT = "COR_LOGOUT";

// Sign
export const SGN_SET_USER = "SGN_SET_USER";

// Settings
export const STG_SET_ORGANIZATION_OWNERED = "STG_SET_ORGANIZATION_OWNERED";

// Organization
export const ORG_SET_ORGANIZATION = "ORG_SET_ORGANIZATION";
export const ORG_EDIT_ORGANIZATION = "ORG_EDIT_ORGANIZATION";
export const ORG_CHANGE_MEMBER_ROLE = "ORG_CHANGE_MEMBER_ROLE";
export const ORG_ADD_MEMBER = "ORG_ADD_MEMBER";
export const ORG_REMOVE_MEMBER = "ORG_REMOVE_MEMBER";
export const ORG_SET_TYPE_SESSIONS = "ORG_SET_TYPE_SESSIONS";
export const ORG_ADD_TYPE_SESSION = "ORG_ADD_TYPE_SESSION";
export const ORG_EDIT_TYPE_SESSION = "ORG_EDIT_TYPE_SESSION";
export const ORG_DELETE_TYPE_SESSION = "ORG_DELETE_TYPE_SESSION";
export const ORG_SET_SESSIONS = "ORG_SET_SESSIONS";
export const ORG_ADD_SESSIONS = "ORG_ADD_SESSIONS";
export const ORG_EDIT_SESSION = "ORG_EDIT_SESSION";
export const ORG_DELETE_SESSION = "ORG_DELETE_SESSION";
export const ORG_SET_FORUM = "ORG_SET_FORUM";
export const ORG_ADD_FORUM_CATEGORY = "ORG_ADD_FORUM_CATEGORY";
export const ORG_EDIT_FORUM_CATEGORY = "ORG_EDIT_FORUM_CATEGORY";
export const ORG_DELETE_FORUM_CATEGORY = "ORG_DELETE_FORUM_CATEGORY";
export const ORG_EDIT_FORUM_CATEGORY_POSITION =
  "ORG_EDIT_FORUM_CATEGORY_POSITION";
export const ORG_ADD_FORUM_CATEGORY_SUBJECT = "ORG_ADD_FORUM_CATEGORY_SUBJECT";
export const ORG_EDIT_FORUM_SUBJECT = "ORG_EDIT_FORUM_SUBJECT";
export const ORG_DELETE_FORUM_SUBJECT = "ORG_DELETE_FORUM_SUBJECT";
export const ORG_EDIT_FORUM_SUBJECT_POSITION =
  "ORG_EDIT_FORUM_SUBJECT_POSITION";

// DASHBOARD
export const DASH_SET_ORGANIZATIONS = "DASH_SET_ORGANIZATIONS";
export const DASH_SET_ORGANIZATION = "DASH_SET_ORGANIZATION";
export const DASH_SET_ORGANIZATION_SESSIONS = "DASH_SET_ORGANIZATION_SESSIONS";
export const DASH_SET_ORGANIZATION_MEMBERS = "DASH_SET_ORGANIZATION_MEMBERS";
export const DASH_SET_SESSIONS = "DASH_SET_SESSIONS";
export const DASH_SET_SESSION = "DASH_SET_SESSION";
export const DASH_SET_SESSION_USERS = "DASH_SET_SESSION_USERS";
export const DASH_SET_USER_PRESENT_SESSION = "DASH_SET_USER_PRESENT_SESSION";
export const DASH_REMOVE_USER_PRESENT_SESSION =
  "DASH_REMOVE_USER_PRESENT_SESSION";
export const DASH_ADD_REGISTERED = "DASH_ADD_REGISTERED";
export const DASH_REMOVE_REGISTERED = "DASH_REMOVE_REGISTERED";
export const DASH_PUSH_TAKEN_REGISTERED = "DASH_PUSH_TAKEN_REGISTERED";
export const DASH_ADD_COMMENT = "DASH_ADD_COMMENT";
export const DASH_SET_FORUM = "DASH_SET_FORUM";
export const DASH_SET_FORUM_SUBJECT = "DASH_SET_FORUM_SUBJECT";
export const DASH_ADD_FORUM_SUBJECT_TALK = "DASH_ADD_FORUM_SUBJECT_TALK";
export const DASH_SET_FORUM_TALK = "DASH_SET_FORUM_TALK";
export const DASH_ADD_FORUM_TALK_MESSAGE = "DASH_ADD_FORUM_TALK_MESSAGE";
